name: demo
on: push
jobs:
   first-job: 
       runs-on: ubuntu-latest
       steps:
          - name: run linux command
            run: |
               ls -lrt 
               echo "Hello -world --- demo"
   second-job:
      needs: first-job
      uses: ./.github/workflows/local.yaml
       
